language: node_js
node_js:
- 10.1.0
notifications:
  email: false
  slack:
    rooms:
      secure: CZ3ia+9u+KYfdlwuez3Ph+bU5jyQ+Jab+yRjhjDnx8XC+IVq9q9IUA1ypgDfhvb3bURXPap/LTQH39PQHmWhgYNHhgbHlB2cAt1McxOBG5OfCNuNvkDO2WdO6RdQgXNeG1QC/X0qkhvjiXgbUvnw8SO2AjofzzCgBaoIbQIsnT8VDe4xO+5Ifj+T5jlg8dsnexvtGVXDfTnRtWlkFtV85ZzirB0T3oUXmfWs2A0iHvZaSHiQsPolSPTFO0O73tewKnHUXI1wMp3OYbxrTrrsjwNzq1uTwG34Je/wxbtfgOBqougLW8D1P0ljuaSJMVVgfBo7xE11ZP9tTyBzrw+HXZN5y6r4SwIYKwcIMNMGnZXHU7DwIUgYa5417iJgAEKmMzveQCumvM30+G6RSKWqr5MTLegY3kXGyh2XfgIPD4ZGdBazLe6EgHJWPYkkolXJ4z26tUgOQhNgKOu99/TKPCTrhGTJS7fctgpuBXgCf7qnyMiH1Jb5VuLIAaYSYkCu4MlKahm/16/TUERrR9BZuK6NgTSGa9YLqY8guj6lB6r52xDnOZmr3X9FfvAVv2valcIEmO1LkAH+Lr/jBngyj4pPSrxLmeICTI2bTqj33cAIXcUEuQJa6aOF2z0QLT/5D5ok4y0o/hWO03SKt3jb9QSEs2BekBR38dYa1ucEFNk=
